services:
  - type: web
    name: smart-planner-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
